---
# Tasks to manage AEP (Attachable Entity Profiles) with read_csv
- name: "Read CSV AEP"
  read_csv:
    path: "{{ csv_dir }}/aep.csv"
    delimiter: ','
  register: aep_csv
  when: (csv_dir + '/aep.csv') is file

- name: "Display detected AEP "
  debug:
    msg: "AEP to process: {{ aep_csv.list | map(attribute='aep') | list }}"
  when: aep_csv is defined and aep_csv.list is defined

- name: "Create AEP"
  cisco.aci.aci_aep:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    aep: "{{ item.aep }}"
    description: "{{ item.description | default(omit) }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ aep_csv.list }}"
  when: 
    - aep_csv is defined
    - aep_csv.list is defined
    - item.aep is defined
    - item.aep | length > 0
  tags:
    - aep
    - aci_aep

