---
# Tasks to manage associations AEP-Domain with read_csv
- name: "Read CSV AEP to Domain"
  read_csv:
    path: "{{ csv_dir }}/aep_to_domain.csv"
    delimiter: ','
  register: aep_to_domain_csv
  when: (csv_dir + '/aep_to_domain.csv') is file

- name: "Display detected associations AEP-Domain "
  debug:
    msg: "Associations AEP-Domain to process: {{ aep_to_domain_csv.list | map(attribute='aep') | list }}"
  when: aep_to_domain_csv is defined and aep_to_domain_csv.list is defined

- name: "Associate AEP to Domain"
  cisco.aci.aci_aep_to_domain:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    aep: "{{ item.aep }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    # vm_provider: "{{ item.vm_provider | default(omit) }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ aep_to_domain_csv.list }}"
  when: 
    - aep_to_domain_csv is defined
    - aep_to_domain_csv.list is defined
    - item.aep is defined
    - item.aep | length > 0
    - item.domain is defined
    - item.domain | length > 0
    - item.domain_type is defined
    - item.domain_type | length > 0
  tags:
    - aep_domain_associations
    - aci_aep