---
# Tasks to manage Physical Domains with read_csv
- name: "Read CSV Physical Domains"
  read_csv:
    path: "{{ csv_dir }}/domain.csv"
    delimiter: ','
  register: domain_csv
  when: (csv_dir + '/domain.csv') is file

- name: "Display detected Physical Domains "
  debug:
    msg: "Physical Domains to process: {{ domain_csv.list | map(attribute='domain') | list }}"
  when: domain_csv is defined and domain_csv.list is defined

- name: "Create Physical Domain"
  cisco.aci.aci_domain:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ domain_csv.list }}"
  when: 
    - domain_csv is defined
    - domain_csv.list is defined
    - item.domain is defined
    - item.domain | length > 0
    - item.domain_type is defined
    - item.domain_type | length > 0
  tags:
    - physical_domains
    - aci_domain

