---
# TÃÂ¢ches pour gÃÂ©rer les associations interface selector to switch policy leaf profile avec read_csv
- name: "Read CSV Interface Selector to Switch Policy Leaf Profile"
  read_csv:
    path: "{{ csv_dir }}/int_sel_to_switch_policy_leaf.csv"
    delimiter: ','
  register: int_sel_to_switch_policy_leaf_csv
  when: (csv_dir + '/int_sel_to_switch_policy_leaf.csv') is file

- name: "Afficher les associations Interface Selector to Switch Policy Leaf Profile dÃÂ©tectÃÂ©es"
  debug:
    msg: "Associations ÃÂ  traiter: {{ int_sel_to_switch_policy_leaf_csv.list | length }} associations"
  when: int_sel_to_switch_policy_leaf_csv is defined and int_sel_to_switch_policy_leaf_csv.list is defined

- name: "{{ item.leaf_profile }} Ã¢Â {{ item.interface_selector }} - CrÃÂ©er l'association"
  cisco.aci.aci_interface_selector_to_switch_policy_leaf_profile:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    leaf_profile: "{{ item.leaf_profile }}"
    interface_selector: "{{ item.interface_selector }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ int_sel_to_switch_policy_leaf_csv.list }}"
  when:
    - int_sel_to_switch_policy_leaf_csv is defined
    - int_sel_to_switch_policy_leaf_csv.list is defined
    - item.leaf_profile is defined
    - item.interface_selector is defined
    - item.leaf_profile | length > 0
    - item.interface_selector | length > 0
