---
# Tâches pour gérer les policies CDP avec read_csv
- name: "Read CSV CDP Policies"
  read_csv:
    path: "{{ csv_dir }}/interface_policy_cdp.csv"
    delimiter: ','
  register: cdp_policy_csv
  when: (csv_dir + '/interface_policy_cdp.csv') is file

- name: "Afficher les policies CDP détectées"
  debug:
    msg: "Policies CDP à traiter: {{ cdp_policy_csv.list | map(attribute='cdp_policy') | list }}"
  when: cdp_policy_csv is defined and cdp_policy_csv.list is defined

- name: "{{ item.cdp_policy }} - Manage CDP interface policies (cdp:IfPol)"
  cisco.aci.aci_interface_policy_cdp:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    cdp_policy: "{{ item.cdp_policy }}"
    admin_state: "{{ item.admin_state }}"
    description: "{{ item.description | default('') }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ cdp_policy_csv.list }}"
  when:
    - cdp_policy_csv is defined
    - cdp_policy_csv.list is defined
    - item.cdp_policy is defined
    - item.cdp_policy | length > 0
