---
# Tasks to manage policies Spanning Tree with read_csv
- name: "Read CSV Spanning Tree Policies"
  read_csv:
    path: "{{ csv_dir }}/interface_policy_spanning_tree.csv"
    delimiter: ','
  register: stp_policy_csv
  when: (csv_dir + '/interface_policy_spanning_tree.csv') is file

- name: "Display detected policies Spanning Tree "
  debug:
    msg: "Policies Spanning Tree to process: {{ stp_policy_csv.list | map(attribute='stp_policy') | list }}"
  when: stp_policy_csv is defined and stp_policy_csv.list is defined

- name: "Manage Spanning Tree Policy"
  cisco.aci.aci_interface_policy_spanning_tree:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    stp_policy: "{{ item.stp_policy }}"
    bpdu_guard: "{{ item.bpdu_guard | default('disabled') }}"
    bpdu_filter: "{{ item.bpdu_filter | default('disabled') }}"
    description: "{{ item.description | default('') }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ stp_policy_csv.list }}"
  when:
    - stp_policy_csv is defined
    - stp_policy_csv.list is defined
    - item.stp_policy is defined
    - item.stp_policy | length > 0
