---
# Tasks to manage interface policy leaf profiles with read_csv
- name: "Read CSV Interface Policy Leaf Profiles"
  read_csv:
    path: "{{ csv_dir }}/interface_policy_leaf_profile.csv"
    delimiter: ','
  register: interface_policy_leaf_profile_csv
  when: (csv_dir + '/interface_policy_leaf_profile.csv') is file

- name: "Display detected Interface Policy Leaf Profiles "
  debug:
    msg: "Interface Policy Leaf Profiles to process: {{ interface_policy_leaf_profile_csv.list | map(attribute='interface_profile') | list }}"
  when: interface_policy_leaf_profile_csv is defined and interface_policy_leaf_profile_csv.list is defined

- name: "Create Interface Policy Leaf Profile"
  cisco.aci.aci_interface_policy_leaf_profile:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    interface_profile: "{{ item.interface_profile }}"
    description: "{{ item.description | default('') }}"
    type: "{{ item.type | default('leaf') }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ interface_policy_leaf_profile_csv.list }}"
  when:
    - interface_policy_leaf_profile_csv is defined
    - interface_policy_leaf_profile_csv.list is defined
    - item.interface_profile is defined
    - item.interface_profile | length > 0
  tags:
    - interface_policy_leaf_profile
    - aci_interface_policy_leaf_profile