---
# Task to manage L3Out Interfaces
- name: "Read CSV l3out_interface"
  read_csv:
    path: "{{ csv_dir }}/l3out_interface.csv"
    delimiter: ','
  register: l3out_interface_csv
  when: (csv_dir + '/l3out_interface.csv') is file

- name: "Afficher les L3Out Interfaces dtects"
  debug:
    msg: "L3Out Interfaces  traiter: {{ l3out_interface_csv.list | map(attribute='path_ep') | list }}"
  when: l3out_interface_csv is defined and l3out_interface_csv.list is defined

- name: "Create L3Out Interface"
  cisco.aci.aci_l3out_interface:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    tenant: "{{ item.tenant }}"
    l3out: "{{ item.l3out }}"
    node_profile: "{{ item.node_profile }}"
    interface_profile: "{{ item.interface_profile }}"
    pod_id: "{{ item.pod_id }}"
    node_id: "{{ item.node_id }}"
    path_ep: "{{ item.path_ep }}"
    interface_type: "{{ item.interface_type | default('l3-port') }}"
    encap: "{{ item.encap | default(omit) }}"
    mode: "{{ item.mode | default('regular') }}"
    address: "{{ item.address | default(omit) }}"
    mtu: "{{ item.mtu | default('inherit') }}"
    description: "{{ item.description | default(omit) }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ l3out_interface_csv.list }}"
  when:
    - l3out_interface_csv is defined
    - l3out_interface_csv.list is defined
    - l3out_interface_csv.list | length > 0
    - item.path_ep is defined
    - item.path_ep | length > 0

- name: " Rsum L3Out Interfaces"
  debug:
    msg: " {{ l3out_interface_csv.list | length }} L3Out Interfaces crs"
  when: l3out_interface_csv is defined and l3out_interface_csv.list | length > 0