# L3Out Floating SVI Path Configuration Tasks
# Manages path attributes for floating SVI interfaces

- name: "Read CSV l3out_floating_svi_path"
  read_csv:
    path: "{{ csv_dir }}/l3out_floating_svi_path.csv"
    delimiter: ','
  register: l3out_floating_svi_path_csv
  when: (csv_dir + '/l3out_floating_svi_path.csv') is file

- name: "Display detected L3Out Floating SVI Path "
  debug:
    msg: "L3Out Floating SVI Path to process: {{ l3out_floating_svi_path_csv.list | map(attribute='node_id') | list }}"
  when: l3out_floating_svi_path_csv is defined and l3out_floating_svi_path_csv.list is defined

- name: "Create Floating SVI Path"
  cisco.aci.aci_l3out_floating_svi_path:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    
    tenant: "{{ item.tenant }}"
    l3out: "{{ item.l3out }}"
    node_profile: "{{ item.node_profile }}"
    interface_profile: "{{ item.interface_profile }}"
    pod_id: "{{ item.pod_id }}"
    node_id: "{{ item.node_id }}"
    encap: "{{ item.encap }}"
    access_encap: "{{ item.access_encap | default(omit) }}"
    domain: "{{ item.domain | default(omit) }}"
    domain_type: "{{ item.domain_type | default(omit) }}"
    floating_ip: "{{ item.floating_ip | default(omit) }}"
    # path_type: "{{ item.path_type | default(omit) }}"
    # description: "{{ item.description | default(omit) }}"
    
    state: "{{ deployment_state | default('present') }}"
  loop: "{{ l3out_floating_svi_path_csv.list }}"
  when:
    - l3out_floating_svi_path_csv is defined
    - l3out_floating_svi_path_csv.list is defined
    - item.node_id is defined
    - item.node_id | length > 0