---
# Tasks to manage Match Route Destinations with read_csv
- name: "Read CSV Match Route Destinations"
  read_csv:
    path: "{{ csv_dir }}/match_route_destination.csv"
    delimiter: ','
  register: match_route_destination_csv
  when: (csv_dir + '/match_route_destination.csv') is file

- name: "Display detected Match Route Destinations"
  debug:
    msg: "Match Route Destinations to process: {{ match_route_destination_csv.list | map(attribute='ip') | list }}"
  when: match_route_destination_csv is defined and match_route_destination_csv.list is defined

- name: "Add Match Route Destination"
  cisco.aci.aci_match_route_destination:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true

    tenant: "{{ item.tenant }}"
    match_rule: "{{ item.match_rule }}"
    ip: "{{ item.ip }}"

    # state: "{{ item.state if item.state | length > 0 else global_state }}"
  loop: "{{ match_route_destination_csv.list }}"
  when:
    - match_route_destination_csv is defined
    - match_route_destination_csv.list is defined
    - item.tenant is defined
    - item.match_rule is defined
    - item.ip is defined
    - item.tenant | length > 0
    - item.match_rule | length > 0
    - item.ip | length > 0
