---
# Tasks to manage Match Rules with read_csv
- name: "Read CSV Match Rules"
  read_csv:
    path: "{{ csv_dir }}/match_rule.csv"
    delimiter: ','
  register: match_rule_csv
  when: (csv_dir + '/match_rule.csv') is file

- name: "Display detected Match Rules"
  debug:
    msg: "Match Rules to process: {{ match_rule_csv.list | map(attribute='match_rule') | list }}"
  when: match_rule_csv is defined and match_rule_csv.list is defined

- name: "Create Match Rule"
  cisco.aci.aci_match_rule:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true

    tenant: "{{ item.tenant }}"
    match_rule: "{{ item.match_rule }}"
    description: "{{ item.description | default(omit) }}"

    # state: "{{ item.state if item.state | length > 0 else global_state }}"
  loop: "{{ match_rule_csv.list }}"
  when:
    - match_rule_csv is defined
    - match_rule_csv.list is defined
    - item.tenant is defined
    - item.match_rule is defined
    - item.tenant | length > 0
    - item.match_rule | length > 0
