---
# Tâches pour gérer les Route Control Profiles avec read_csv
- name: "Read CSV Route Control Profiles"
  read_csv:
    path: "{{ csv_dir }}/route_control_profile.csv"
    delimiter: ','
  register: route_control_profile_csv
  when: (csv_dir + '/route_control_profile.csv') is file

- name: "Afficher les Route Control Profiles détectés"
  debug:
    msg: "Route Control Profiles à traiter: {{ route_control_profile_csv.list | map(attribute='route_control_profile') | list }}"
  when: route_control_profile_csv is defined and route_control_profile_csv.list is defined

- name: "{{ item.route_control_profile }} - Créer Route Control Profile (rtctrl:Profile)"
  cisco.aci.aci_route_control_profile:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true

    tenant: "{{ item.tenant }}"
    l3out: "{{ item.l3out }}"
    route_control_profile: "{{ item.route_control_profile }}"

    state: "{{ item.state if item.state | length > 0 else global_state }}"
  loop: "{{ route_control_profile_csv.list }}"
  when:
    - route_control_profile_csv is defined
    - route_control_profile_csv.list is defined
    - item.tenant is defined
    - item.l3out is defined
    - item.route_control_profile is defined
    - item.tenant | length > 0
    - item.l3out | length > 0
    - item.route_control_profile | length > 0
