---
# Tasks to manage Route Control Contexts with read_csv
- name: "Read CSV Route Control Contexts"
  read_csv:
    path: "{{ csv_dir }}/route_control_context.csv"
    delimiter: ','
  register: route_control_context_csv
  when: (csv_dir + '/route_control_context.csv') is file

- name: "Display detected Route Control Contexts"
  debug:
    msg: "Route Control Contexts to process: {{ route_control_context_csv.list | map(attribute='route_control_context') | list }}"
  when: route_control_context_csv is defined and route_control_context_csv.list is defined

- name: "Create Route Control Context"
  cisco.aci.aci_route_control_context:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true

    tenant: "{{ item.tenant }}"
    l3out: "{{ item.l3out }}"
    route_control_profile: "{{ item.route_control_profile }}"
    route_control_context: "{{ item.route_control_context }}"
    action: permit
    order: 0
    match_rule: "{{ item.match_rule }}"

    # state: "{{ item.state if item.state | length > 0 else global_state }}"
  loop: "{{ route_control_context_csv.list }}"
  when:
    - route_control_context_csv is defined
    - route_control_context_csv.list is defined
    - item.tenant is defined
    - item.l3out is defined
    - item.route_control_profile is defined
    - item.route_control_context is defined
    - item.match_rule is defined
    - item.tenant | length > 0
    - item.l3out | length > 0
    - item.route_control_profile | length > 0
    - item.route_control_context | length > 0
    - item.match_rule | length > 0
