---
# Tasks to manage VLAN Pools avec read_csv
- name: "Read CSV VLAN Pools"
  read_csv:
    path: "{{ csv_dir }}/vlan_pool.csv"
    delimiter: ','
  register: vlan_pool_csv
  when: (csv_dir + '/vlan_pool.csv') is file

- name: "Display detected VLAN Pools "
  debug:
    msg: "VLAN Pools to process: {{ vlan_pool_csv.list | map(attribute='pool') | list }}"
  when: vlan_pool_csv is defined and vlan_pool_csv.list is defined

- name: "Create VLAN Pool"
  cisco.aci.aci_vlan_pool:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    state: "{{ item.state | default(global_state) }}"
    pool: "{{ item.pool }}"
    pool_allocation_mode: "{{ item.pool_allocation_mode | default('static') }}"
    description: "{{ item.description | default(omit) }}"
  loop: "{{ vlan_pool_csv.list }}"
  when: 
    - vlan_pool_csv is defined
    - vlan_pool_csv.list is defined
    - item.pool is defined
    - item.pool | length > 0
  tags:
    - vlan_pools
    - aci_vlan_pool

