---
# Tasks to manage VRFs with read_csv
- name: "Read CSV VRFs"
  read_csv:
    path: "{{ csv_dir }}/vrf.csv"
    delimiter: ','
  register: vrf_csv
  when: (csv_dir + '/vrf.csv') is file

- name: "Display detected VRFs"
  debug:
    msg: "VRFs to process: {{ vrf_csv.list | map(attribute='vrf') | list }}"
  when: vrf_csv is defined and vrf_csv.list is defined

- name: "Create VRF"
  cisco.aci.aci_vrf:
    host: "{{ aci_hostname }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: "{{ aci_validate_certs | default(false) }}"
    annotation: ""
    use_ssl: true
    tenant: "{{ item.tenant }}"
    vrf: "{{ item.vrf }}"
    description: "{{ item.description | default(omit) }}"
    state: "{{ item.state | default(global_state) }}"
  loop: "{{ vrf_csv.list }}"
  when: 
    - vrf_csv is defined
    - vrf_csv.list is defined
    - item.vrf is defined
    - item.vrf | length > 0
    - item.tenant is defined
    - item.tenant | length > 0
  tags:
    - vrfs
    - aci_vrf